### ISSUE TITLE
North Star - Research how OPM defines career paths

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/team-design#14]
We need to do a bit of research on how OPM defines career paths.

**Old Trello URL:** https://trello.com/c/ZolGgl3A/36-research-career-paths

**Checklists:**

Checklist - 

   - [x] Talk to April Davis on how OPM defines career paths
   - [x] Talk to Leslie Pollack in HRS on how they define career paths
   - [x] Talk to USA Learning - Will Parantino and Paul Jesukiewicz - they have plans to produce something that could be used with USAJOBS profiles
   - [x] Talk to Jennifer Thibault 18F
   - [x] Write up report capturing who we spoke to, what we heard, and anything we learned/plan to do about it.

**Interview notes:** https://airtable.com/tblWIyPFhJjbncMlU/viwEbRiXPzK0jLYz6

**Attachments:** 

**Comments:**

**Comment by humancompanion** [comment]
@Piglady64 - Career paths, not hiring paths. For example, if you are an IT Specialist and want to become a System Architect, how does OPM guide you to each "next step". 

Also, this is North Star work so, I don't want to steal you for this until I really need to. I'll be reaching out to these folks later this week to setup times to talk to them with the USDS folks.

**Comment by Piglady64** [comment]
I have an interview scheduled with Will Peratino in the Learning Center on 13 Nov.

**Comment by humancompanion** [comment]
Julie to meet with Leslie today (11/26). Met with April but, with a different script.

**Comment by humancompanion** [comment]
@mchung07 and @timtimtimtimofficial to write up a report capturing who we spoke to, what we heard, and anything we learned/plan to do about it.

**Comment by mchung07** [comment]
Final report has been uploaded and reviewed.
