### ISSUE TITLE
North Star: Mission Critical hiring diagram

### ISSUE THREAD

**Issue by timtimtimtimofficial** [USAJOBS/team-design#17]
In OmniGraffle, digitize & refine hand-drawn diagram of Mission Critical hiring future state.

**Comment by humancompanion** [comment]
I owe a revision of this diagram for the team to iterate on.

**Comment by humancompanion** [comment]
![mission critical jobs 2018-10-23-v5](https://user-images.githubusercontent.com/352987/47670894-b85bf380-db84-11e8-8320-648b94aa5c93.png)

This is the current version of the doc. It does need additional annotations from additional docs but, wanted to capture the progress in here.

**Comment by humancompanion** [comment]
This is done for now.
