### ISSUE TITLE
North Star - Heuristic walkthrough of application process

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/team-design#9]
Gang - As part of our North Star project, and to help The Lab out, I would appreciate it if over the next 2-3 days you could go through the application process for The Lab HIF positions: https://www.uat.usajobs.gov/GetJob/ViewDetails/3261297300

Specifically, I'd like us to do a heuristic walk through. So @jenkaczor perhaps can assign us areas to focus on. There are a number of checklists we could use: https://www.nngroup.com/articles/ten-usability-heuristics/, https://www.nngroup.com/articles/ux-expert-reviews/ (see Components of an Expert Review), https://en.wikipedia.org/wiki/Heuristic_evaluation#Gerhardt-Powals.E2.80.99_cognitive_engineering_principles

And yes, I know these are controversial. It's not a substitute for user research and usability testing. But in this context it would help for our team to have fresh eyes on the application process, specifically one that our future fellow designers will go through. This will both help us to know what applicants to The Lab should expect so that we can help supplement their experience and it will help those who haven't been through it recently to be up-to-speed on what the experience is like. In addition, I'm hoping your evaluations will help update our baseline on specific problems with applying.

**Comment by jenkack** [comment]
@humancompanion I grouped screenshots by phase; zip files for each phase are in "Screenshots by phase" row in AT: https://airtable.com/tblEeBmZZTZPn7jrN/viwrFlpmsFDC2H9PA

Please share feedback or confirm this works.
